title: <p align="center"> Saheli Das </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/saheli-das-343bb7147/">LinkedIn</a> |
  <a href="https://github.com/SaheliDas25">GitHub</a>
  


theme: jekyll-theme-minimal
